copyright: Copyright &copy; 2020-Present LGUG2Z
use_directory_urls: false
site_name: Komorebi
site_description: The Tiling Window Manager for Windows
repo_url: https://github.com/LGUG2Z/komorebi
repo_name: LGUG2Z/komorebi
docs_dir: docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
plugins:
  - macros
  - search

nav:
  - Komorebi:
    - index.md
    - Design: design.md
  - Getting started:
    - Installation: installation.md
    - Example configurations: example-configurations.md
  - Common workflows:
    - common-workflows/komorebi-config-home.md
    - common-workflows/active-window-border.md
    - common-workflows/remove-gaps.md
    - common-workflows/ignore-windows.md
    - common-workflows/force-manage-windows.md
    - common-workflows/tray-and-multi-window-applications.md
    - common-workflows/focus-follows-mouse.md
    - common-workflows/mouse-follows-focus.md
    - common-workflows/custom-layouts.md
    - common-workflows/dynamic-layout-switching.md
#    - common-workflows/autohotkey.md
  - Release notes:
    - release/v0-1-22.md
  - Configuration reference: https://komorebi.lgug2z.com/schema
  - CLI reference:
    - cli/quickstart.md
    - cli/start.md
    - cli/stop.md
    - cli/check.md
    - cli/configuration.md
    - cli/whkdrc.md
    - cli/state.md
    - cli/visible-windows.md
    - cli/query.md
    - cli/subscribe-socket.md
    - cli/unsubscribe-socket.md
    - cli/subscribe-pipe.md
    - cli/unsubscribe-pipe.md
    - cli/log.md
    - cli/quick-save-resize.md
    - cli/quick-load-resize.md
    - cli/save-resize.md
    - cli/load-resize.md
    - cli/focus.md
    - cli/move.md
    - cli/minimize.md
    - cli/close.md
    - cli/force-focus.md
    - cli/cycle-focus.md
    - cli/cycle-move.md
    - cli/stack.md
    - cli/resize-edge.md
    - cli/resize-axis.md
    - cli/unstack.md
    - cli/cycle-stack.md
    - cli/move-to-monitor.md
    - cli/cycle-move-to-monitor.md
    - cli/move-to-workspace.md
    - cli/move-to-named-workspace.md
    - cli/cycle-move-to-workspace.md
    - cli/send-to-monitor.md
    - cli/cycle-send-to-monitor.md
    - cli/send-to-workspace.md
    - cli/send-to-named-workspace.md
    - cli/cycle-send-to-workspace.md
    - cli/send-to-monitor-workspace.md
    - cli/focus-monitor.md
    - cli/focus-last-workspace.md
    - cli/focus-workspace.md
    - cli/focus-workspaces.md
    - cli/focus-monitor-workspace.md
    - cli/focus-named-workspace.md
    - cli/cycle-monitor.md
    - cli/cycle-workspace.md
    - cli/move-workspace-to-monitor.md
    - cli/swap-workspaces-with-monitor.md
    - cli/new-workspace.md
    - cli/resize-delta.md
    - cli/invisible-borders.md
    - cli/global-work-area-offset.md
    - cli/monitor-work-area-offset.md
    - cli/focused-workspace-container-padding.md
    - cli/focused-workspace-padding.md
    - cli/adjust-container-padding.md
    - cli/adjust-workspace-padding.md
    - cli/change-layout.md
    - cli/cycle-layout.md
    - cli/load-custom-layout.md
    - cli/flip-layout.md
    - cli/promote.md
    - cli/promote-focus.md
    - cli/retile.md
    - cli/monitor-index-preference.md
    - cli/display-index-preference.md
    - cli/ensure-workspaces.md
    - cli/ensure-named-workspaces.md
    - cli/container-padding.md
    - cli/named-workspace-container-padding.md
    - cli/workspace-padding.md
    - cli/named-workspace-padding.md
    - cli/workspace-layout.md
    - cli/named-workspace-layout.md
    - cli/workspace-custom-layout.md
    - cli/named-workspace-custom-layout.md
    - cli/workspace-layout-rule.md
    - cli/named-workspace-layout-rule.md
    - cli/workspace-custom-layout-rule.md
    - cli/named-workspace-custom-layout-rule.md
    - cli/clear-workspace-layout-rules.md
    - cli/clear-named-workspace-layout-rules.md
    - cli/workspace-tiling.md
    - cli/named-workspace-tiling.md
    - cli/workspace-name.md
    - cli/toggle-window-container-behaviour.md
    - cli/toggle-pause.md
    - cli/toggle-tiling.md
    - cli/toggle-float.md
    - cli/toggle-monocle.md
    - cli/toggle-maximize.md
    - cli/restore-windows.md
    - cli/manage.md
    - cli/unmanage.md
    - cli/reload-configuration.md
    - cli/watch-configuration.md
    - cli/complete-configuration.md
    - cli/window-hiding-behaviour.md
    - cli/cross-monitor-move-behaviour.md
    - cli/toggle-cross-monitor-move-behaviour.md
    - cli/unmanaged-window-operation-behaviour.md
    - cli/float-rule.md
    - cli/manage-rule.md
    - cli/initial-workspace-rule.md
    - cli/initial-named-workspace-rule.md
    - cli/workspace-rule.md
    - cli/named-workspace-rule.md
    - cli/identify-object-name-change-application.md
    - cli/identify-tray-application.md
    - cli/identify-layered-application.md
    - cli/remove-title-bar.md
    - cli/toggle-title-bars.md
    - cli/identify-border-overflow-application.md
    - cli/active-window-border.md
    - cli/active-window-border-colour.md
    - cli/active-window-border-width.md
    - cli/active-window-border-offset.md
    - cli/focus-follows-mouse.md
    - cli/toggle-focus-follows-mouse.md
    - cli/mouse-follows-focus.md
    - cli/toggle-mouse-follows-focus.md
    - cli/ahk-library.md
    - cli/ahk-app-specific-configuration.md
    - cli/pwsh-app-specific-configuration.md
    - cli/format-app-specific-configuration.md
    - cli/fetch-app-specific-configuration.md
    - cli/application-specific-configuration-schema.md
    - cli/notification-schema.md
    - cli/socket-schema.md
    - cli/static-config-schema.md
    - cli/generate-static-config.md
    - cli/enable-autostart.md
    - cli/disable-autostart.md
