[package]
name = "komorebi-shortcuts"
version = "0.1.0"
edition = "2024"

[dependencies]
whkd-parser = { git = "https://github.com/LGUG2Z/whkd", rev = "v0.2.9" }
whkd-core = { git = "https://github.com/LGUG2Z/whkd", rev = "v0.2.9" }

eframe = { workspace = true }
dirs = { workspace = true }